### ISSUE TITLE
Doesn't work with emulated aux directory

### ISSUE THREAD

**Issue by matthewelmer** [sasozivanovic/memoize#15]
Using texlive means that `latexmk` must emulate the aux directory. Unfortunately, doing so seems to break this library. Set these options in your `.latexmkrc` to reproduce the bug:
```
$aux_dir = "aux";
$emulate_aux = 1;
```

You'll get nothing but a cryptic error message such as the following:
```
Package 
memoize Error: Extraction of externs from document "<document name>" using method "per
l" was unsuccessful.
```

(I have installed the necessary perl library, and setting `extract=python` didn't make the issue go away.)

**Comment by jccollins** [comment]
It turns out there even without the use of an aux directory, a special configuration is needed to get latexmk working properly with Memoize.   But some enhancements were needed to latexmk to make this configuration straightforward and clean, especially when an aux directory is used.  A suitable rc file will be included in the next release of latexmk (v. 4.84).

**Comment by sasozivanovic** [comment]
I'm assuming this works now ... if not, please re-open.
