### ISSUE TITLE
Mildly confusing statement in section 5.5

### ISSUE THREAD

**Issue by amonakov** [sasozivanovic/memoize#7]
In the `Extern extraction` section there are the following paragraphs:

> In LaTeX and ConTeXt, the selected method is executed at the end of loading the package.
Afterwards, the key is disabled. If you really need to invoke extraction in the preamble, or again,
write `extract`/<*method*>.

> When invoked from a `\mmzset` in the document preamble, this key immediately *executes* the given
extraction method. In the preamble incarnation, the key may be invoked without a value to
execute the previously selected method.

I am not sure what the takeaway from the last statement should be for the end user. In LaTeX, `\mmzset` cannot be invoked like that, because it happens inside of `\includepackage` and the use of this key without an argument is disabled afterwards, as explained in the first paragraph.

**Comment by sasozivanovic** [comment]
Thank you. The documentation was confusing since it documented two different stages in the development of the package.

The documentation is now updated to reflect the latest (1.1.0) version, which allows one to use `extract` in the preamble without an argument after `extract=no` among the package options, as I suggested in the discussion on #6.
